POST http://127.0.0.1:8080/students/register
Content-Type: application/json

{
    "name": "Samira",
    "email": "kalaf@abdul.com",
    "birth": "1/10/2000",
    "password": "oiafjnsdoijfa"
}

###
POST http://127.0.0.1:8080/students/login
Content-Type: application/json

{
    "email": "kalaf@abdul.com",
    "password": "oiafjnsdoijfa"
}

###

GET http://127.0.0.1:8080/logged
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.U2FtaXJh.TAjE8hE5T4APSh4nuZQGrsEnIxB-JanN6qXioWS7Kqo

###
GET http://127.0.0.1:8080/students/63c891d0f0df36dad3a30de4


###
DELETE http://127.0.0.1:8080/students/63cc3cf99a01381639b57618

###
PUT  http://127.0.0.1:8080/students/63cc3cf99a01381639b57618
Content-Type: application/json

{
    "name": "Sakalaf",
    "email": "kaa@fabdul.com",
    "studentBirth": "01/01/2009",


}

//PRODUCTION
###

GET https://bookclubapi-pytl.onrender.com/students

###
GET https://bookclubapi-pytl.onrender.com/students/63cc86a2f12425d2c758bbf2
###

POST https://bookclubapi-pytl.onrender.com/students
Content-Type: application/json

{
    "name": "Kamala",
    "email": "kalaf@abdul.com"
}


###

PUT https://bookclubapi-pytl.onrender.com/students/63cc86a2f12425d2c758bbf2
Content-Type: application/json

{
    "name": "Samira",
    "email": "kalaf@abdul.com"
    "birth": "1/10/2000"
    "password": "oiafjnsdoijfa"
}

###
GET https://bookclubapi-pytl.onrender.com/students/63c8a7a69d358718af191217

###
DELETE https://bookclubapi-pytl.onrender.com/students/63cc86a2f12425d2c758bbf2