POST http://127.0.0.1:8080/
Content-Type: application/json

{
"firstname": "abduh",
"lastName": "kalaf",
"email": "jose@cavalcanti.net",
"favoriteColor": "brown",
"birthday": "30/12/2009"
}

###

GET http://127.0.0.1:8080/

###
GET http://127.0.0.1:8080/63bf72a171a288433c16b99b


###
DELETE http://127.0.0.1:8080/63bf743c1db8f098c279c75a

###
PATCH http://127.0.0.1:8080/63bf729c71a288433c16b999
Content-Type: application/json

{
    "firstName": "john",
    "birthday":  "31/11/2018"
}

//PRODUCTION
###

GET https://cse341-mj3e.onrender.com/getcontacts

###
GET https://cse341-mj3e.onrender.com/getcontacts/63bf729c71a288433c16b999

###

POST https://cse341-mj3e.onrender.com/
Content-Type: application/json

{
"firstname": "Maria",
"lastName": "Abduh",
"email": "jose@cavalcanti.net",
"favoriteColor": "pink",
"birthday": "30/12/1989"
}

###

PATCH https://cse341-mj3e.onrender.com/63bfff9364cd2b974c495528
Content-Type: application/json

{
    "firstName": "Diana",
    "birthday":  "30/11/1932"
}

###
GET https://cse341-mj3e.onrender.com/getcontacts/63bfff9364cd2b974c495528

###
DELETE https://cse341-mj3e.onrender.com/63bfff9364cd2b974c495528