POST http://127.0.0.1:8080/students
Content-Type: application/json

{
    "name": "abduh Kalaf 2"
}

###

GET http://127.0.0.1:8080/students

###
GET http://127.0.0.1:8080/students/63c891d0f0df36dad3a30de4


###
DELETE http://127.0.0.1:8080/students/63c891d0f0df36dad3a30de4

###
PUT  http://127.0.0.1:8080/students/63c89c7acc8058e429b6750d
Content-Type: application/json

{
    "name": "Abduh Kalaf"
}

//PRODUCTION
###

GET https://cse341-mj3e.onrender.com/getcontacts

###
GET https://cse341-mj3e.onrender.com/getcontacts/63bf729c71a288433c16b999

###

POST https://cse341-mj3e.onrender.com/
Content-Type: application/json

{
"firstname": "Maria",
"lastName": "Abduh",
"email": "jose@cavalcanti.net",
"favoriteColor": "pink",
"birthday": "30/12/1989"
}

###

PATCH https://cse341-mj3e.onrender.com/63bfff9364cd2b974c495528
Content-Type: application/json

{
    "firstName": "Diana",
    "birthday":  "30/11/1932"
}

###
GET https://cse341-mj3e.onrender.com/getcontacts/63bfff9364cd2b974c495528

###
DELETE https://cse341-mj3e.onrender.com/63bfff9364cd2b974c495528